import "../scss/app.scss";
import "./bootstrap";
import AnimatedHeader from "./components/animatedHeader";
import SwiperBanner from "./components/swiperBanner";
import SwiperFuncBox from "./components/swiperFuncBox";
import SwiperNews from "./components/newsSlider";
import SwiperProducts from "./components/productsSlider";
import Gotop from "./components/gotop";
import "./components/textareaCounter";
import playVideo from "./components/aboutVideoOpen";
import increaseCounter from "./components/increaseCounter";
import SwiperQualify from "./components/qualifySlider";
import qualifyOpenImg from "./components/qualifyOpenImg";
import SwiperHistory from "./components/historySlider";
import setMapPosition from "./components/setMapPosition";
import openSerialNumber from "./components/openAuthenticationModal";
import SwiperAboutNews from "./components/swiperAboutNews";
import SwiperForward from "./components/forwardSlider";
import openAccordion from "./components/accordion";
import showVideo from "./components/showVideo";
import openSelect from "./components/openSelect";
import breadcrumbs from "./components/breadcrumbs";
import setMaskHeight from "./components/setProductMaskHeight";
import swiperDeviceCard from "./components/swiperDeviceCard";
import showMoreParameters from "./components/showMoreParemeters";
import swiperDeviceMaterial from "./components/deviceMaterialSlider";
import openFaqPopup from "./components/openFaqPopup";
import initYM from "./components/serviceMap";
import findDriver from "./components/drivers-search";
import showDownloadFiles from "./components/showDownloadFiles";

function main() {
	AnimatedHeader();
	SwiperBanner();
	SwiperFuncBox();
	SwiperNews();
	SwiperProducts();
	Gotop();
	playVideo();
	increaseCounter();
	SwiperQualify();
	qualifyOpenImg();
	SwiperHistory();
	setMapPosition();
	openSerialNumber();
	SwiperAboutNews();
	SwiperForward();
	openAccordion();
	showVideo();
	openSelect();
	breadcrumbs();
	setMaskHeight();
	swiperDeviceCard();
	showMoreParameters();
	swiperDeviceMaterial();
	openFaqPopup();
	findDriver();
	showDownloadFiles();
	initYM();
}

document.addEventListener("DOMContentLoaded", main);
